#pragma once

#ifndef WORLDCONSTANTS_H
#define WORLDCONSTANTS_H


#define TREE_ADULTAGE				25
#define TREE_DIEAGE					500
#define TREE_DISAPPEARAGE			600
#define TREE_REPRODUCT_BONUS		0.75
#define TREE_REPRODUCT_CHANCE		(int)(((TREE_DIEAGE - TREE_ADULTAGE) * TREE_REPRODUCT_BONUS))
#define TREE_REPRODUCT_RAD			3
#define TREE_REPRODUCT_DIAM			(TREE_REPRODUCT_RAD * 2 + 1)
#define TREE_REPRODUCT_TRIES		1
#define TREE_DIE_CHANCE				10
#define TREE_GROW_CHANCE			500
#define BUSH_GROW_CHANCE			100
#define BUSH_DIEAGE					30
#define BUSH_DIE_CHANCE				5

#define HUMIDITY_PENALTY			0.99f
#define HUMIDITY_BORDER				50
#define PRODUCTIVITY_PENALTY		0.999f

#define TEMPERATURE_PENALTY			0.98f
#define TEMPERATURE_MIN				(-30.0f)
#define TEMPERATURE_MAX				(50.0f)
#define TEMPERATURE_RANGE			(abs(TEMPERATURE_MIN) + abs(TEMPERATURE_MAX))
#define TEMPERATURE_BORDER_FREEZE	0
#define TEMPERATURE_BORDER_TUNDRA	7
#define TEMPERATURE_BORDER_SAVANNA	26
#define TEMPERATURE_BORDER_TROPICS	36
#define TEMPERATURE_BORDER_DESERT	46

#define DEEPWATER_DEPTH				200

#define AFFORESTCOST_BUSH			1
#define AFFORESTCOST_TREE			3


#endif // WORLDCONSTANTS_H
