#pragma once

#ifndef WORLDCONSTANTS_H
#define WORLDCONSTANTS_H


#define TREE_DIE_CHANCE				10
#define TREE_REPRODUCT_RAD			5

#define HUMIDITY_PENALTY			0.99f
#define HUMIDITY_BORDER				50
#define PRODUCTIVITY_PENALTY		0.999f

#define TEMPERATURE_PENALTY			0.98f
#define TEMPERATURE_MIN				(-30.0f)
#define TEMPERATURE_MAX				(50.0f)
#define TEMPERATURE_RANGE			(abs(TEMPERATURE_MIN) + abs(TEMPERATURE_MAX))

#define DEEPWATER_DEPTH				200
#define MOUNTAIN_HEIGHT_KOEF		0.5
#define HILL_HEIGHT_KOEF			0.3


#endif // WORLDCONSTANTS_H
