#pragma once

#ifndef WORLDCONSTANTS_H
#define WORLDCONSTANTS_H


#define TREE_DIE_CHANCE				10

#define HUMIDITY_PENALTY			0.99f
#define HUMIDITY_BORDER				50
#define PRODUCTIVITY_PENALTY		0.999f

#define TEMPERATURE_PENALTY			0.98f
#define TEMPERATURE_MIN				(-30.0f)
#define TEMPERATURE_MAX				(50.0f)
#define TEMPERATURE_RANGE			(abs(TEMPERATURE_MIN) + abs(TEMPERATURE_MAX))
#define TEMPERATURE_BORDER_FREEZE	0
#define TEMPERATURE_BORDER_TUNDRA	7
#define TEMPERATURE_BORDER_SAVANNA	26
#define TEMPERATURE_BORDER_TROPICS	36
#define TEMPERATURE_BORDER_DESERT	46

#define DEEPWATER_DEPTH				200


#endif // WORLDCONSTANTS_H
